# Default values for sqrl-planner

global:
  config:
    # The hostname defaults to the name of the Kubernetes service. Changes this
    # if not using the shared MongoDB service.
    MONGODB_HOST: sqrl-planner-mongodb
    MONGODB_PORT: "27017"

sqrl-server:
  image:
    repository: sverch02/sqrl-server
    tag: latest
  config:
      # The hostname of the Gator service.
    GATOR_HOST: http://sqrl-planner-gator-app:5000

gator-app:
  image:
    repository: sverch02/gator-app
    tag: 0.1.1
  config:
    # The root URL for the Swagger API documentation, relative to the root of the
    # web server. If not set or empty, the Swagger UI will not be available, and
    # no documentation will be generated.
    API_DOCS_URL: /docs/
