{{- include "common.configMap" (list . "gator-app.configMap") }}
{{- define "gator-app.configMap" -}}
{{- $top := first . }}
data:
  # The bind port for the gunicorn server
  PORT: {{ $top.Values.service.port | quote }}
  # Defaults are given by $top.Values.global.config
  # (Shared config values for all subcharts)
  {{- if $top.Values.global.config }}
  {{- toYaml $top.Values.global.config | nindent 2 }}
  {{- end }}
  # Override with $top.Values.config
  # (Specific config values for this subchart)
  {{- if $top.Values.config }}
  {{- toYaml $top.Values.config | nindent 2 }}
  {{- end }}
{{- end }}