{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "gator-app.deployment") }}

{{- define "gator-app.deployment" -}}
{{- $top := first . }}
{{- $deployment := index . 1 }}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $top.Template.BasePath "/configmap.yaml") $top | sha256sum }}
        checksum/secret: {{ include (print $top.Template.BasePath "/secret.yaml") $top | sha256sum }}
    spec:
      containers:
      - {{- include "common.container" (list $top $deployment "gator-app.deployment.container") | nindent 8 }}
      {{- include "gator-app.deployment.volumes" (list $top $deployment) | nindent 6 }}
{{- end }}

{{- define "gator-app.deployment.volumes" -}}
volumes:
- name: tmp
  emptyDir: {}
{{- end }}

{{- define "gator-app.deployment.container" -}}
{{- include "gator-app.container" . | nindent 0 }}
{{- $values := index . 1 }}

{{- $livenessProbe := $values.livenessProbe | default dict }}
{{- $readinessProbe := $values.readinessProbe | default dict }}
{{- if ($livenessProbe.enabled | default true) }}
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: {{ $livenessProbe.initialDelaySeconds | default 30 }}
  periodSeconds: {{ $livenessProbe.periodSeconds | default 10 }}
  timeoutSeconds: {{ $livenessProbe.timeoutSeconds | default 5 }}
  successThreshold: {{ $livenessProbe.successThreshold | default 1 }}
  failureThreshold: {{ $livenessProbe.failureThreshold | default 3 }}
{{- end }}
{{- if ($readinessProbe.enabled | default true) }}
readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: {{ $readinessProbe.initialDelaySeconds | default 30 }}
  periodSeconds: {{ $readinessProbe.periodSeconds | default 10 }}
  timeoutSeconds: {{ $readinessProbe.timeoutSeconds | default 5 }}
  successThreshold: {{ $readinessProbe.successThreshold | default 1 }}
  failureThreshold: {{ $readinessProbe.failureThreshold | default 3 }}
{{- end }}
{{- end }}
