{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "gator-app.deployment") }}

{{- define "gator-app.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (append . "gator-app.container") | nindent 8 }}
{{- end }}

{{- define "gator-app.container" -}}
ports:
  - name: http
    containerPort: 80
    protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
{{- end }}