{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "gator-app.deployment") }}

{{- define "gator-app.deployment" -}}
{{- $top := first . }}
{{- $deployment := index . 1 }}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $top.Template.BasePath "/configmap.yaml") $top | sha256sum }}
        checksum/secret: {{ include (print $top.Template.BasePath "/secret.yaml") $top | sha256sum }}
    spec:
      containers:
      - {{- include "common.container" (list $top $deployment "gator-app.deployment.container") | nindent 8 }}
      {{- include "gator-app.deployment.volumes" (list $top $deployment) | nindent 6 }}
{{- end }}

{{- define "gator-app.deployment.volumes" -}}
volumes:
- name: tmp
  emptyDir: {}
{{- end }}

{{- define "gator-app.deployment.container" -}}
{{- $top := first . }}
ports:
- name: http
  containerPort: {{ $top.Values.service.port }}
  protocol: TCP
livenessProbe:
  httpGet:
    path: /ping
    port: http
readinessProbe:
  httpGet:
    path: /ping
    port: http
volumeMounts:
- name: tmp
  mountPath: /tmp
envFrom:
- configMapRef:
    name: {{ include "common.fullname" $top }}
- secretRef:
    name: {{ include "common.fullname" $top }}
{{- end }}