{{- include "common.secret" (list . "gator-app.secret") }}
{{- define "gator-app.secret" -}}
{{- $top := first . }}
data:
  {{- $secrets := merge ($top.Values.global.secrets | default dict) ($top.Values.secrets | default dict) }}
  {{- range $key, $value := $secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}