{{- include "common.secret" (list . "sqrl-server.secret") }}
{{- define "sqrl-server.secret" -}}
{{- $top := first . }}
data:
  {{- $secrets := merge ($top.Values.global.secrets | default dict) ($top.Values.secrets | default dict) }}
  {{- range $key, $value := $secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}